### ISSUE TITLE
Just a big blank window

### ISSUE THREAD

**Issue by dzg** [ganeshrvel/openmtp#249]
Installed via `brew` on macOS 10.15.7.

Launching just gives a giant empty window.

Running from Terminal:
```/Applications/OpenMTP.app/Contents/MacOS/OpenMTP
GVA encoder info: AMD performance mode : 2
GVA encoder info: deleteSCDMetalContext : texture cache hits: 0, misses: 0
2021/10/18 14:48:27 OpenSession failed: LIBUSB_ERROR_NOT_FOUND; attempting reset
2021/10/18 14:48:31 OpenSession failed: LIBUSB_ERROR_NOT_FOUND; attempting reset
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10d626539]

runtime stack:
runtime.throw(0x10d341e1e, 0x2a)
	runtime/panic.go:1116 +0x72
runtime.sigpanic()
	runtime/signal_unix.go:704 +0x48c

goroutine 17 [syscall, locked to thread]:
runtime.cgocall(0x10d2d2b80, 0xc00013bbc8, 0x200000003)
	runtime/cgocall.go:133 +0x5b fp=0xc00013bb98 sp=0xc00013bb60 pc=0x10d10f4fb
github.com/ganeshrvel/usb._Cfunc_libusb_claim_interface(0x7fcac80a0000, 0x7fca00000000, 0x0)
	_cgo_gotypes.go:229 +0x4d fp=0xc00013bbc8 sp=0xc00013bb98 pc=0x10d1f2b8d
github.com/ganeshrvel/usb.(*DeviceHandle).ClaimInterface.func1(0x7fcac80a0000, 0x10d1f3c00, 0x10d2d3500)
	github.com/ganeshrvel/usb/usb.go:643 +0x56 fp=0xc00013bbf8 sp=0xc00013bbc8 pc=0x10d1f6a56
github.com/ganeshrvel/usb.(*DeviceHandle).ClaimInterface(0x7fcac80a0000, 0xc00013bc00, 0x10d1f68ef, 0x7fcae6f295e0)
	github.com/ganeshrvel/usb/usb.go:643 +0x39 fp=0xc00013bc20 sp=0xc00013bbf8 pc=0x10d1f5499
github.com/ganeshrvel/go-mtpfs/mtp.(*Device).claim(0xc000114100, 0x7fcac80a0000, 0x0)
	github.com/ganeshrvel/go-mtpfs/mtp/mtp.go:140 +0x45 fp=0xc00013bc98 sp=0xc00013bc20 pc=0x10d220ec5
github.com/ganeshrvel/go-mtpfs/mtp.(*Device).Open(0xc000114100, 0x0, 0x0)
	github.com/ganeshrvel/go-mtpfs/mtp/mtp.go:170 +0xfa fp=0xc00013bd50 sp=0xc00013bc98 pc=0x10d2210fa
github.com/ganeshrvel/go-mtpfs/mtp.(*Device).Configure(0xc000114100, 0x0, 0x0)
	github.com/ganeshrvel/go-mtpfs/mtp/mtp.go:646 +0xf3 fp=0xc00013bda8 sp=0xc00013bd50 pc=0x10d224513
github.com/ganeshrvel/go-mtpx.Initialize(0x0, 0x0, 0x0, 0x10d3440c8)
	github.com/ganeshrvel/go-mtpx/main.go:31 +0x72 fp=0xc00013be10 sp=0xc00013bda8 pc=0x10d231112
main._initialize(0x0, 0x0, 0x0, 0x0)
	command-line-arguments/helpers.go:36 +0x2e fp=0xc00013be40 sp=0xc00013be10 pc=0x10d2ce9ee
main.Initialize(0x10e734010)
	command-line-arguments/kalam.go:27 +0x45 fp=0xc00013be78 sp=0xc00013be40 pc=0x10d2cf925
main._cgoexpwrap_a73366901861_Initialize(0x10e734010)
	_cgo_gotypes.go:62 +0x2b fp=0xc00013be90 sp=0xc00013be78 pc=0x10d2cf56b
runtime.call32(0x0, 0x70000e2eddc0, 0x70000e2ede58, 0x8)
	runtime/asm_amd64.s:540 +0x3e fp=0xc00013bec0 sp=0xc00013be90 pc=0x10d172d3e
runtime.cgocallbackg1(0x0)
	runtime/cgocall.go:332 +0x1a5 fp=0xc00013bf58 sp=0xc00013bec0 pc=0x10d10f8c5
runtime.cgocallbackg(0x0)
	runtime/cgocall.go:207 +0xc5 fp=0xc00013bfc0 sp=0xc00013bf58 pc=0x10d10f665
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	runtime/asm_amd64.s:794 +0x9b fp=0xc00013bfe0 sp=0xc00013bfc0 pc=0x10d1744bb
runtime.goexit()
	runtime/asm_amd64.s:1374 +0x1 fp=0xc00013bfe8 sp=0xc00013bfe0 pc=0x10d174741

goroutine 18 [syscall, locked to thread]:
github.com/ganeshrvel/usb._Cfunc_libusb_reset_device(0x7fcac8088000, 0x7fca00000000)
	_cgo_gotypes.go:607 +0x49
github.com/ganeshrvel/usb.(*DeviceHandle).Reset.func1(0x7fcac8088000, 0x3c)
	github.com/ganeshrvel/usb/usb.go:713 +0x4d
github.com/ganeshrvel/usb.(*DeviceHandle).Reset(0x7fcac8088000, 0x28, 0xc000095d88)
	github.com/ganeshrvel/usb/usb.go:713 +0x30
github.com/ganeshrvel/go-mtpfs/mtp.(*Device).Configure(0xc000114280, 0x0, 0x10d118e00)
	github.com/ganeshrvel/go-mtpfs/mtp/mtp.go:640 +0x213
github.com/ganeshrvel/go-mtpx.Initialize(0x10d640d00, 0x10d298a01, 0x100010d31ba80, 0x10d3440c8)
	github.com/ganeshrvel/go-mtpx/main.go:31 +0x72
main._initialize(0x0, 0x0, 0x10d636108, 0x10d4ae520)
	command-line-arguments/helpers.go:36 +0x2e
main.Initialize(0x10e734098)
	command-line-arguments/kalam.go:27 +0x45
main._cgoexpwrap_a73366901861_Initialize(0x10e734098)
	_cgo_gotypes.go:62 +0x2b
Checking for update
Update for version 3.1.15 is not available (latest version: 3.1.15, downgrade is disallowed).
```

**Comment by ganeshrvel** [comment]
Please comment your Laptop model, config and OS version

**Comment by JeremyH66** [comment]
Same issue. MacBook Air (mid 2012) macOS Catalina 10.15.7 (19H1419)

**Comment by dzg** [comment]
> Please comment your Laptop model, config and OS version

Not a laptop. iMac Pro (2017) macOS 10.15.7 as mentioned above

thanks

**Comment by githubjsorg** [comment]
Having the same issue. Initially the window is blank, then release announcements appears, then window blanks out again ([see screen recording](https://imgur.com/a/CbV9cA6)). Tried both .app downloaded from main page and brew install. Same issue.

System Info
10.15.7 (19H1713)
MacBook Pro (16-inch, 2019)

**Comment by githubjsorg** [comment]
More testing found that the window didn't blank out until the phone was connected to USB. I was able to clear the "what's new" but as soon as I plugged in my android device, the window blanked out.

**Comment by githubjsorg** [comment]
Looks like this project has been abandoned.

**Comment by ganeshrvel** [comment]
I will be making a release for the M1 MacBook in a couple of weeks. Let's see if that fixes this issue?

**Comment by githubjsorg** [comment]
Yes. I have tried that too. Here is a screen recording.
https://imgur.com/1UMYy5J

**Comment by umara123** [comment]
I'm getting this same issue after upgrading to MacOS **Monterey** on my intel MacBookPro 16-inch, 2019. The app is now unstable and unusable. This previously was not an issue for me with the same laptop on MacOS Big Sur.

**Comment by ganeshrvel** [comment]
See if this version helps?
https://github.com/ganeshrvel/openmtp-testflight/blob/main/OpenMTP-3.2.0/OpenMTP-3.2.0-alpha.1-mac.zip

**Comment by githubjsorg** [comment]
That one just opens and immediately closes without even showing a window. And no, I did not have an android device connected. Crash report [https://pastebin.com/41rKgTYN](url)

**Comment by ganeshrvel** [comment]
I am looking into this issue. It should be an electron issue. I will fix this ASAP.

**Comment by githubjsorg** [comment]
Any update on this? Do you have another build I can try?

**Comment by githubjsorg** [comment]
> I am looking into this issue. It should be an electron issue. I will fix this ASAP.

Hi @ganeshrvel. Do you have a fix I can test?

**Comment by ganeshrvel** [comment]
@githubjsorg could you send me the log file

1. Open your Terminal and run the following code:

```zip -r -X ~/Desktop/OpenMTP-log.zip "$HOME/Library/Application Support/io.ganeshrvel.openmtp/logs/"```

2. Attach the file OpenMTP-log.zip found in your Desktop folder here.


Also, could you install the other versions of the app from the Releases list and let me know what was the latest version that worked for you?
Releases list: [https://github.com/ganeshrvel/openmtp/releases](https://github.com/ganeshrvel/openmtp/releases)
